server:
  port: 9090
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:9000/Apartment_Management"
    username: root
    password: duong123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
jwt:
  signerKey: "U5IeSrMYMWbhjirxzw/OeuPWRgdWPSGueiQVa8Bn5+VSxDx0vDvH0l4fsl1p2EOk"
  valid-duration: 1 #second
  refreshable-duration: 2 #second
